# Reviewdog

name: reviewdog

on: [pull_request]

jobs:
  golangci-lint:
    name: review
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: true
      - name: Run golangci-lint with reviewdog
        uses: reviewdog/action-golangci-lint@v2.0.3
        with:
          golangci_lint_flags: "--timeout=10m"
